export const editorBlocks = {
  PARA: "para",
  HEADING: "heading",
  SUB_HEADING: "sub_heading",
  CODE: "code",
  ORDERED_LIST: "ordered_list",
  UNORDERED_LIST: "unordered_list",
  COLLAPSIBLE: "collapsible",
  TABLE: "table",
  DIVIDER: "divider",
  QUOTE: "quote",
  TIP: "tip",
  CAUTION: "caution",
  NOTE: "note",
  IMAGE: "image",
  EMBED: "embed",
  GITHUB: "github",
  YOUTUBE: "youtube",
  CODESANDBOX: "codesandbox",
  CODEPEN: "codepen",
  MARKDOWN: "markdown",
  DRAFT: "draft",
} as const;

export const editorTools = {
  UNDO: "undo",
  REDO: "redo",
  BOLD: "bold",
  ITALIC: "italic",
  UNDERLINE: "underline",
  LINE_THROUGH: "line_through",
  LINK: "link",
  INLINE_CODE: "inline_code",
  HIGHLIGHT: "highlight",
  SUBSCRIPT: "subscript",
  SUPERSCRIPT: "superscript",
  MENTION: "mention",
  INDENT: "indent",
  OUTDENT: "outdent",
  CONVERT: "convert",
  COPY_LINK: "copy_link",
  GRAB: "grab",
  DELETE: "delete",
  AI: "ai",

  TOGGLE_CASE: "case_toggle",
  LOWERCASE: "case_lower",
  UPPERCASE: "case_upper",
  FONT: "font_family",
  TEXT_FORMAT_REMOVE: "text_format_remove",
} as const;
